import re
import json

def process_file(filename, valid_indices, new_questions, var_name):
    with open(filename, 'r', encoding='utf-8') as f:
        content = f.read()
    
    match = re.search(r'const\s+' + var_name + r'\s*=\s*(\[[\s\S]*?\]);', content)
    if not match: return
    array_str = match.group(1)
    objects = re.findall(r'(\{[^\}]+\})', array_str)
    kept_objects = [objects[i] for i in valid_indices]
    
    for q in new_questions:
        obj_str = f'{{ theme: "EM", question: "{q["question"]}", options: {json.dumps(q["options"], ensure_ascii=False)}, correct: {q["correct"]}, justification: "{q["justification"]}" }}'
        kept_objects.append(obj_str)
        
    final_objects = []
    for i, obj in enumerate(kept_objects):
        obj = re.sub(r'question:\s*"\d+\.\s*', f'question: "{i+1}. ', obj)
        final_objects.append("  " + obj)
        
    final_js = f"const {var_name} = [\n" + ",\n".join(final_objects) + "\n];\n"
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(final_js)
    print("Updated", filename)

new_v1 = [
    {"question": "Según el modelo de Plutchik de la 'rueda de las emociones', las emociones que se sitúan adyacentes (juntas) en el círculo...", "options": ["Son completamente opuestas", "Se parecen más entre sí que las que están alejadas o en oposición", "Generan conflicto cognitivo", "Se cancelan mutuamente"], "correct": 1, "justification": "En el modelo de Plutchik, la cercanía en el círculo refleja similitud entre las emociones."},
    {"question": "Para Paul Ekman, el número de emociones básicas universales es:", "options": ["Cuatro", "Ocho", "Seis", "Diez"], "correct": 2, "justification": "Ekman sugirió seis emociones básicas universales: miedo, asco, enfado, sorpresa, felicidad y tristeza."},
    {"question": "El Modelo Procesual de la Regulación Emocional de Gross sitúa la 'Supresión' en qué momento del proceso?", "options": ["Al principio, modificando la situación", "Durante la valoración cognitiva", "Al final, como modulación de la respuesta", "En el despliegue atencional"], "correct": 2, "justification": "La supresión se aplica una vez que la respuesta emocional ya se ha desencadenado."},
    {"question": "A nivel fisiológico, el uso constante de la estrategia de Supresión emocional tiene como efecto:", "options": ["Reducir la tasa cardíaca", "Aumentar la respuesta fisiológica", "Relajar la musculatura por completo", "Ningún efecto medible"], "correct": 1, "justification": "Ocultar la emoción no reduce su activación, de hecho, incrementa la respuesta fisiológica por el esfuerzo de inhibición."}
]

new_v2 = [
    {"question": "¿Cuál es la diferencia en duración entre una emoción y un estado de ánimo?", "options": ["La emoción dura meses, el estado de ánimo minutos", "La emoción dura segundos a horas; el estado de ánimo dura horas, días e incluso semanas", "Ambos duran lo mismo", "La emoción es crónica, el estado de ánimo es breve"], "correct": 1, "justification": "Las emociones son respuestas más breves e intensas, mientras que los estados de ánimo son más difusos y duraderos."},
    {"question": "En la metáfora del carro alado, la regulación emocional a lo largo de la historia...", "options": ["Nunca ha sido estudiada", "Ha sido entendida como la falta de dominio que hace caer al auriga", "Ha sido representada por el auriga que debe controlar la pareja de caballos para concretar sus metas", "Solo se refiere al caballo blanco"], "correct": 2, "justification": "Desde la antigüedad (Platón) se entiende que la falta de dominio emocional nos hace perder el equilibrio, ilustrando la importancia de la regulación emocional."},
    {"question": "Según la teoría de Schachter y Singer, la activación fisiológica (arousal) sirve para:", "options": ["Darle nombre a la emoción", "Energizar la emoción y determinar su intensidad, mientras que la cognición determina su cualidad", "Apagar el sistema simpático", "Ocultar la emoción"], "correct": 1, "justification": "El arousal nos da la fuerza de la emoción, y la interpretación cognitiva del contexto le pone la etiqueta (cualidad)."},
    {"question": "Un estudio demostró que mujeres y hombres reportan niveles similares de experiencia emocional subjetiva. Sin embargo...", "options": ["Los hombres muestran más activación parasimpática", "Las mujeres tienen más tendencia a expresar las emociones", "Los hombres lloran más frecuentemente", "Las mujeres no sienten asco"], "correct": 1, "justification": "Aunque la experiencia y fisiología son similares, la cultura modula una mayor expresión externa en las mujeres."},
    {"question": "Los estudios revelaron que los japoneses, en comparación con los estadounidenses, al ver películas desagradables acompañados de un científico...", "options": ["Gritaban más fuerte", "Ocultaban más sus expresiones negativas esbozando una sonrisa", "Lloraban desconsoladamente", "No miraban la pantalla"], "correct": 1, "justification": "Esto demuestra que la cultura influye en la intensidad y en cómo se dirigen o enmascaran las emociones en público."},
    {"question": "En la teoría de Cannon-Bard, se critica que pone demasiado énfasis en...", "options": ["La amígdala", "La médula espinal", "El tálamo", "El córtex prefrontal"], "correct": 2, "justification": "La teoría asume que el tálamo es el principal centro de reparto de señales emocionales, ignorando otras estructuras complejas demostradas posteriormente."},
    {"question": "Un argumento en contra de la teoría de James-Lange es que...", "options": ["Las personas con pérdida de sensibilidad corporal o parálisis muscular profunda siguen experimentando emociones", "El corazón late muy rápido", "El cerebro no procesa emociones", "Llorar es inútil"], "correct": 0, "justification": "Si la emoción dependiera únicamente del feedback del cuerpo, la pérdida sensorial eliminaría la emoción, pero no es así."},
    {"question": "¿En qué condiciones las personas toman peores decisiones vitales, según la evidencia neuropsicológica?", "options": ["Cuando piensan demasiado", "Cuando están desconectadas de sus emociones y señales corporales afectivas", "Cuando sienten miedo transitorio", "Cuando usan reevaluación cognitiva"], "correct": 1, "justification": "Las emociones actúan como señales eficaces y guías rápidas para la toma de decisiones."},
    {"question": "En el modelo de la rueda de las emociones de Plutchik, la intensidad de la emoción...", "options": ["Es siempre la misma", "Varía según el color de los ojos", "Disminuye al avanzar hacia la parte inferior o periférica del modelo, haciendo las distinciones menos marcadas", "Aumenta en el centro y se vuelve puramente cognitiva"], "correct": 2, "justification": "En el cono de Plutchik, las emociones más extremas están arriba/centro, y se diluyen hacia abajo."},
    {"question": "¿Qué demostró el experimento de Schachter y Singer con la inyección que causaba activación atípica?", "options": ["Que la droga causaba somnolencia", "Que los participantes interpretaban su activación como euforia o ira basándose en la conducta del cómplice presente en la sala", "Que todos se enojaban independientemente del contexto", "Que la amígdala se apagaba"], "correct": 1, "justification": "Al no tener explicación para su arousal, usaron claves ambientales (el cómplice) para etiquetar su emoción."},
    {"question": "A pesar de las críticas a la teoría de James-Lange, un fenómeno actual que apoya en parte que la fisiología conduce a la emoción es...", "options": ["La depresión genética", "El desarrollo de trastornos de pánico o fobias a partir de interpretaciones de cambios físicos internos", "La esquizofrenia", "La amnesia anterógrada"], "correct": 1, "justification": "En el pánico, una aceleración cardíaca provoca el miedo subjetivo."}
]

new_v3 = [
    {"question": "La Reevaluación Cognitiva tiene el efecto positivo de:", "options": ["Aumentar la represión de recuerdos", "Reducir el comportamiento expresivo, disminuir el sentimiento negativo y disminuir la respuesta fisiológica", "Incrementar la tensión arterial a largo plazo", "Fingir calma por fuera aunque por dentro haya pánico"], "correct": 1, "justification": "Al cambiar el significado, todo el proceso emocional se suaviza, incluyendo la fisiología, sin costos añadidos."},
    {"question": "En contraste con la Supresión, la Reevaluación Cognitiva...", "options": ["Genera rechazo social", "Provoca amnesia del evento", "No tiene costes sociales ni de memoria", "Empeora la salud física en el día a día"], "correct": 2, "justification": "La reevaluación no interfiere con la memoria ni daña las relaciones interpersonales."},
    {"question": "El metaanálisis de Buhle et al. (2014) mostró que la reevaluación cognitiva produce a nivel cerebral...", "options": ["Un infarto de tálamo", "Una hiperactivación del cerebelo", "Una disminución de la actividad de la amígdala", "El crecimiento del cuerpo calloso"], "correct": 2, "justification": "Confirmó que el reappraisal cognitivo reduce exitosamente la activación de la estructura generadora de la emoción (amígdala)."},
    {"question": "¿Qué creencias favorecen una mejor regulación de nuestras emociones?", "options": ["Creer que la emoción es un destino inalterable", "Creer que las emociones se pueden modificar y aprender a regular mejor con la práctica", "Creer que las emociones negativas deben ser ignoradas siempre", "Creer que la razón anula las emociones"], "correct": 1, "justification": "Las personas con creencias de maleabilidad emocional (mindset de crecimiento) regulan mejor y se frustran menos."},
    {"question": "La estrategia de 'Desplazamiento de la Atención' en el modelo de Gross implica:", "options": ["Dormirse en medio del peligro", "Fijar la mirada en la amenaza", "Enfocarse en los aspectos que sí funcionan o son positivos en lugar de la amenaza potencial", "Reevaluar las consecuencias vitales de la situación"], "correct": 2, "justification": "Cambiar el foco atencional (ej. mirar el calor humano y no el caos) ayuda a regular la emoción antes de la valoración."},
    {"question": "En el modelo de regulación de Gross, tener linternas preparadas y comida de emergencia para no entrar en pánico en un apagón es un ejemplo de:", "options": ["Supresión expresiva", "Reevaluación cognitiva", "Modificación de la Situación", "Evitación pura"], "correct": 2, "justification": "Al alterar la situación ambiental (tener recursos), se previene o altera la generación del miedo desde la raíz."},
    {"question": "La vía baja de la emoción postulada por LeDoux se especializa en...", "options": ["Emociones complejas como el odio y el amor", "Emociones más simples como gustos, disgustos y respuestas instintivas de miedo", "La empatía y la culpa", "El cálculo de probabilidades matemáticas del riesgo"], "correct": 1, "justification": "Al evitar la corteza, la vía baja es un atajo para emociones rudimentarias esenciales para la supervivencia inmediata."},
    {"question": "La vía alta de las emociones...", "options": ["Pasa por la corteza cerebral, donde analizamos y etiquetamos la información antes de ordenar una respuesta", "Es más rápida pero comete errores", "No pasa por el tálamo", "Genera respuestas automáticas en milisegundos sin pensamiento"], "correct": 0, "justification": "Es la ruta detallada y consciente para emociones complejas que requieren análisis."},
    {"question": "El psicólogo Richard Lazarus sostenía que...", "options": ["La fisiología y la cognición no interactúan", "Cierta actividad o valoración cognitiva es condición necesaria y suficiente para toda emoción", "Las preferencias no son procesos cognitivos", "Los animales no tienen emociones al carecer de lenguaje"], "correct": 1, "justification": "Lazarus defendió que siempre hay un 'appraisal' (evaluación), aunque sea esquemático y no consciente, para que surja la emoción."},
    {"question": "Una de las críticas a la teoría de la emoción de Schachter y Singer es que...", "options": ["Las personas no saben hablar", "Sugiere que el arousal es un estado indiferenciado, pero ya existen evidencias de patrones fisiológicos específicos para distintas emociones", "El puente colgante era seguro", "Las vitaminas anulan el efecto"], "correct": 1, "justification": "Algunos estudios modernos sugieren que no toda la fisiología es igual; el miedo y la ira tienen ligeras diferencias autonómicas."},
    {"question": "El malestar emocional intenso se equipara evolutivamente con:", "options": ["Un fallo del sistema", "El dolor físico, actuando como una señal de que algo vital está en riesgo y necesita atención", "Una alucinación sensorial", "El bienestar espiritual"], "correct": 1, "justification": "Sin estas señales aversivas, podríamos ignorar daños sociales o físicos graves."},
    {"question": "Si una persona experimenta frustración intensa, esta emoción suele indicar que...", "options": ["Una meta o deseo importante se encuentra bloqueado", "Está completamente relajado", "Ha logrado el éxito absoluto", "Su sistema nervioso parasimpático está hiperactivo"], "correct": 0, "justification": "Las emociones señalan el estado de nuestras metas. La frustración indica obstrucción de objetivos."},
    {"question": "El objetivo principal de los procesos de regulación emocional es:", "options": ["Eliminar cualquier sentimiento permanentemente", "Producir un cambio en nuestras emociones, ya sea reduciéndolas o aumentándolas (tanto positivas como negativas)", "Volvernos seres puramente racionales", "Solo reducir la ansiedad en exámenes"], "correct": 1, "justification": "La regulación busca ajustar la intensidad, duración o cualidad de la emoción de forma adaptativa, sea cual sea la dirección."},
    {"question": "A nivel de salud física en el día a día, el uso constante de reevaluación cognitiva...", "options": ["Predice peores resultados", "No tiene impacto fisiológico", "Se asocia a mejor salud física y menos problemas cardiovasculares", "Aumenta la probabilidad de desarrollar úlceras"], "correct": 2, "justification": "Al reducir la cronicidad del estrés simpático, protege el sistema cardiovascular a largo plazo."},
    {"question": "A nivel social, la supresión emocional crónica se relaciona con...", "options": ["Relaciones interpersonales más cercanas e íntimas", "Relaciones sociales menos cercanas y mayor costo social", "Un aumento del carisma", "Mejor entendimiento mutuo"], "correct": 1, "justification": "Esconder las emociones hace que los demás nos perciban como fríos o inauténticos, dificultando la conexión íntima."},
    {"question": "El experimento del puente colgante de Dutton y Aaron demostró:", "options": ["La validez del polígrafo", "El fenómeno de la transferencia de excitación o atribución errónea del arousal fisiológico", "Que el miedo cura las fobias", "La supresión expresiva en alturas"], "correct": 1, "justification": "El miedo causado por la altura se sumó y se confundió con atracción sexual hacia la entrevistadora."},
    {"question": "¿Cuál es la causa habitual que desencadena una emoción?", "options": ["No tiene causa conocida", "Factores puramente genéticos", "Suele ser clara y externa (un evento identificable)", "Suele ser difusa e inidentificable"], "correct": 2, "justification": "A diferencia del estado de ánimo, la emoción es una reacción a un desencadenante claro y específico."},
    {"question": "La vía directa (baja) de la emoción conecta...", "options": ["El cerebelo con la corteza", "Los receptores sensoriales directamente al músculo", "El tálamo directamente con la amígdala pasando por alto el córtex", "La médula con el hipocampo"], "correct": 2, "justification": "El tálamo envía un borrador burdo a la amígdala para que detone el sistema de alarma inmediatamente."},
    {"question": "¿Qué teoría sostiene que primero evaluamos de manera primitiva y luego sentimos?", "options": ["Cannon-Bard", "James-Lange", "Valoración cognitiva de Lazarus", "Schachter puro"], "correct": 2, "justification": "Para Lazarus, la cognición (evaluación), consciente o no, precede a todo el proceso emocional."},
    {"question": "Cuando usamos el 'Desplazamiento de la Atención' para regular emociones...", "options": ["Cambiamos nuestra respiración", "Alteramos la forma en la que dirigimos nuestro foco a los estímulos del ambiente", "Golpeamos una pared", "Ocultamos nuestra sonrisa"], "correct": 1, "justification": "Nos focalizamos en lo menos amenazante para evitar que la percepción desencadene la emoción completa."},
    {"question": "La amígdala se considera central porque...", "options": ["Regula la digestión lenta", "Es un centro de procesamiento emocional crucial, especialmente para emociones como el miedo", "Solo guarda recuerdos alegres", "Controla el habla consciente"], "correct": 1, "justification": "La amígdala orquesta la respuesta de supervivencia ante amenazas detectadas."},
    {"question": "¿Qué asume el modelo del afecto de Russell sobre las emociones?", "options": ["Que son colores", "Que se estructuran en un espacio de valencia y activación", "Que son infinitas e independientes", "Que solo existen cuatro"], "correct": 1, "justification": "Cualquier emoción puede describirse según cuánto nos activa (arousal) y cuán agradable/desagradable es (valencia)."},
    {"question": "El hecho de que personas ciegas de nacimiento muestren expresiones faciales emocionales típicas apoya:", "options": ["La teoría de que se aprende por tacto", "La teoría de Darwin de que las expresiones son innatas y vestigios evolutivos de la especie", "Que las emociones son falsas", "Que las emociones cambian en cada país"], "correct": 1, "justification": "Si no han podido ver caras ajenas, su sonrisa o cara de asco debe venir codificada en los genes humanos."},
    {"question": "¿Qué papel juega el tálamo en la teoría de Cannon-Bard?", "options": ["Solo procesa el dolor", "Ninguno, es ignorado", "Actúa como un relé que envía señales simultáneas al córtex (para la consciencia) y al sistema nervioso autónomo (para el cuerpo)", "Es el generador único de la alegría"], "correct": 2, "justification": "El tálamo bifurca la información para que experiencia y fisiología ocurran al mismo tiempo."},
    {"question": "¿Qué evidencia sugiere que el estado de activación (arousal) no determina totalmente la emoción?", "options": ["Que no hay hormonas", "Que personas con el corazón latiendo rápido por causas artificiales a menudo dicen no experimentar 'verdaderas emociones'", "Que los animales no tienen cerebro", "Que la respiración no cambia"], "correct": 1, "justification": "Inyectarse epinefrina sin un contexto ambiental claro te hace sentir activado ('como si tuviera miedo') pero no produce la emoción real completa."},
    {"question": "¿Qué ocurre si una persona reevalúa la situación cognitivamente frente a un comentario desagradable?", "options": ["Suda muchísimo más", "Pierde la amistad al instante", "Reduce su enfado sintiendo que el otro 'no está en posición de juzgar', bajando su respuesta fisiológica", "Crea un trauma reprimido"], "correct": 2, "justification": "Alterar la interpretación del comentario desarma la amenaza y, por ende, frena la respuesta autonómica de ira."},
    {"question": "Una característica distintiva de la Supresión Expresiva es que...", "options": ["Previene que el sujeto perciba el evento aversivo", "Las emociones reales siguen sintiéndose igual por dentro aunque la cara se muestre impasible", "Aumenta la felicidad genuina", "Solo se puede usar en niños"], "correct": 1, "justification": "El intento consciente de ocultar la expresión no apaga la emoción subjetiva; el sentimiento negativo persiste inalterado (o incluso aumenta)."}
]

valid_v1 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 27, 28]
valid_v2 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 13, 14, 18, 25, 26, 27, 28, 29]
valid_v3 = [15, 24, 28]

process_file('/home/ares/Psicologia/CME/.preguntas/q_t3.js', valid_v1, new_v1, 'qT3')
process_file('/home/ares/Psicologia/CME/.preguntas/q_t3_v2.js', valid_v2, new_v2, 'qT3_v2')
process_file('/home/ares/Psicologia/CME/.preguntas/q_t3_v3.js', valid_v3, new_v3, 'qT3_v3')
