import re
import json

def process_file(filename, valid_indices, new_questions, var_name):
    with open(filename, 'r', encoding='utf-8') as f:
        content = f.read()
    
    match = re.search(r'const\s+' + var_name + r'\s*=\s*(\[[\s\S]*?\]);', content)
    if not match: return
    array_str = match.group(1)
    objects = re.findall(r'(\{[^\}]+\})', array_str)
    kept_objects = [objects[i] for i in valid_indices]
    
    for q in new_questions:
        obj_str = f'{{ theme: "MO", question: "{q["question"]}", options: {json.dumps(q["options"], ensure_ascii=False)}, correct: {q["correct"]}, justification: "{q["justification"]}" }}'
        kept_objects.append(obj_str)
        
    final_objects = []
    for i, obj in enumerate(kept_objects):
        obj = re.sub(r'question:\s*"\d+\.\s*', f'question: "{i+1}. ', obj)
        final_objects.append("  " + obj)
        
    final_js = f"const {var_name} = [\n" + ",\n".join(final_objects) + "\n];\n"
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(final_js)
    print("Updated", filename)

new_v1 = [
    {"question": "Según William James, el comportamiento humano puede explicarse a partir de tres elementos principales:", "options": ["Genética, ambiente y cultura", "Instintos, hábitos y voluntad", "Refuerzos, castigos e incentivos", "Emociones, pensamientos y acciones"], "correct": 1, "justification": "James consideraba que los instintos (predisposiciones innatas) junto con los hábitos y la voluntad estructuran la conducta humana."},
    {"question": "¿Qué demostró el experimento de Birch (1956) con las ratas que no lamían a sus crías?", "options": ["Que las ratas no tienen instintos", "Que etiquetar conductas complejas simplemente como 'instinto maternal' era insuficiente, ya que la conducta dependía del olor a tejidos vaginales", "Que el castigo elimina los instintos", "Que las ratas son agresivas por naturaleza"], "correct": 1, "justification": "Birch mostró la importancia de estudiar los mecanismos concretos en lugar de usar etiquetas instintivas."},
    {"question": "Para explicar conductas instintivas simples en la actualidad, los etólogos prefieren usar el concepto de:", "options": ["Patrones de acción fijos", "Pulsiones innatas primarias", "Reflejos incondicionados de Pavlov", "Voluntad genética"], "correct": 0, "justification": "Los patrones de acción fijos son respuestas automáticas heredadas ante estímulos específicos, como el bostezo contagioso."},
    {"question": "En la teoría de Hull (Reducción de pulsiones), ¿qué es la homeostasis?", "options": ["Un estado de alerta máxima", "El estado de equilibrio biológico interno que el cuerpo trabaja activamente por mantener", "La ausencia total de motivación", "Una emoción social"], "correct": 1, "justification": "El objetivo de reducir la pulsión (hambre, sed) es recuperar este estado de estabilidad biológica (homeostasis)."},
    {"question": "Según la teoría de la activación óptima, ¿qué ocurre si la activación es demasiado alta?", "options": ["Alcanzamos el flow", "Buscamos más estimulación para mejorar", "Aparece aburrimiento", "Aparecen estrés y ansiedad, por lo que tratamos de reducirla"], "correct": 3, "justification": "Niveles muy altos de activación cognitiva o fisiológica resultan aversivos e interfieren con el rendimiento."},
    {"question": "Para Eysenck, las personas introvertidas prefieren ambientes menos estimulantes porque:", "options": ["Odian a la gente", "Tienen niveles basales de activación más altos, alcanzando su nivel óptimo antes", "Tienen niveles basales de activación más bajos", "Carecen de necesidades sociales"], "correct": 1, "justification": "Al estar ya altamente activados por defecto, necesitan menos estímulos externos para llegar al óptimo y evitan la sobreestimulación."}
]

new_v2 = [
    {"question": "Algunos autores sugieren que las personas con TDAH buscan constantemente estimulación porque:", "options": ["Tienen un exceso de activación", "Podrían presentar niveles bajos de activación basal y necesitan estimulación para alcanzar su nivel óptimo de funcionamiento", "No tienen necesidades psicológicas", "Carecen de instintos"], "correct": 1, "justification": "Explicaría su necesidad de movimiento o búsqueda de novedad como una forma de autorregular su arousal bajo."},
    {"question": "En la jerarquía de Maslow, ¿qué tipo de necesidades son las de afiliación?", "options": ["Fisiológicas", "Necesidades sociales (vínculos afectivos y pertenencia)", "De seguridad", "De estima"], "correct": 1, "justification": "Buscan superar la soledad y establecer vínculos con otras personas o grupos."},
    {"question": "Una crítica metodológica importante a la pirámide de Maslow es que:", "options": ["Tiene demasiados niveles", "Sus conceptos y categorías son demasiado ambiguas para ser estudiadas científicamente con precisión", "Solo se aplica a niños", "No incluye las necesidades fisiológicas"], "correct": 1, "justification": "Al dejar mucho margen para la interpretación, dificulta la investigación empírica rigurosa."},
    {"question": "En la motivación intrínseca, la conducta se realiza porque...", "options": ["Se busca una recompensa material", "Se quiere evitar un castigo severo", "La propia actividad resulta interesante, satisfactoria o se hace por el gusto de hacerla", "Alguien nos obliga"], "correct": 2, "justification": "La fuente de motivación nace en la persona; la ejecución de la tarea es la recompensa misma."},
    {"question": "Las teorías orgánicas de la motivación (Deci y Ryan) conciben al ser humano como:", "options": ["Un mecanismo pasivo que responde solo a estímulos", "Un organismo activo, dinámico y con tendencias naturales hacia el crecimiento y desarrollo personal", "Una caja negra incomprensible", "Un animal movido únicamente por pulsiones de supervivencia"], "correct": 1, "justification": "Se oponen al mecanicismo clásico y postulan que buscamos activamente aprender y adaptarnos al entorno."},
    {"question": "En el contexto de la Teoría de la Autodeterminación, 'Autonomía' significa:", "options": ["Hacer las cosas sin ayuda de nadie", "Deseo de sentir que nuestras acciones dependen de nosotros mismos, eligiendo libremente según nuestros valores", "Aislarse socialmente", "Poder controlar a otras personas"], "correct": 1, "justification": "Es la necesidad de ser el origen de la propia conducta, no de independencia absoluta."},
    {"question": "En el experimento clásico de sobrejustificación (Lepper, Greene, Nisbett), ¿qué pasó con los niños a los que se pagó por dibujar?", "options": ["Empezaron a dibujar mejor", "Mostraron muy poco interés en jugar con rotuladores posteriormente en ausencia de premios", "Mantuvieron su motivación intrínseca", "Regalaron sus dibujos"], "correct": 1, "justification": "La recompensa externa socavó su interés interno preexistente por la actividad creativa."},
    {"question": "En la teoría de la Autodeterminación, la 'regulación externa' se caracteriza por:", "options": ["Estar basada en valores personales profundos", "Ser la forma más controlada de motivación extrínseca, dependiente directamente de recompensas o presiones externas", "Ser sinónimo de motivación intrínseca", "Basarse en el sentimiento de culpa"], "correct": 1, "justification": "Es el tipo de motivación donde la acción ocurre pura y exclusivamente para conseguir un premio o evitar un castigo inmediato."},
    {"question": "Un estudiante que estudia mucho para evitar sentirse culpable frente a sus padres actúa guiado por una regulación...", "options": ["Externa", "Integrada", "Intrínseca", "Introyectada"], "correct": 3, "justification": "En la regulación introyectada, la presión no viene de fuera directamente, sino de una interiorización parcial en forma de 'debería' o culpa."},
    {"question": "Un estudiante que estudia una asignatura aburrida porque sabe que es crucial para su futura carrera profesional muestra una regulación...", "options": ["Externa", "Introyectada", "Identificada", "Desmotivada"], "correct": 2, "justification": "La regulación identificada ocurre cuando valoras la utilidad de la actividad para tus propias metas a largo plazo, aunque no te divierta."},
    {"question": "Según el enfoque cognitivo de la motivación, la conducta se activa por la discrepancia entre:", "options": ["Instinto y hábito", "El estado actual y el estado deseado/ideal", "Emoción y fisiología", "Recompensa y castigo"], "correct": 1, "justification": "Percibir la diferencia entre cómo estamos y cómo queremos estar genera tensión motivacional para actuar y reducir esa distancia."},
    {"question": "Según la teoría de Locke y Latham, las metas más eficaces para motivar el rendimiento deben ser:", "options": ["Específicas, difíciles/desafiantes y aceptadas por la persona", "Abstractas, fáciles e impuestas", "Generales e inalcanzables", "Fáciles y sin límite de tiempo"], "correct": 0, "justification": "Metas como 'voy a estudiar dos horas diarias' motivan mucho más que 'voy a hacerlo lo mejor posible'."},
    {"question": "Para que el establecimiento de metas sea realmente efectivo, se necesita un factor adicional clave durante la ejecución:", "options": ["Un castigo", "Feedback o retroalimentación sobre el progreso", "Disonancia cognitiva", "Un premio económico enorme"], "correct": 1, "justification": "Sin saber si nos estamos acercando a la meta, no podemos ajustar nuestro esfuerzo o sentir la competencia de avanzar."},
    {"question": "Bandura distinguió en su teoría cognitiva dos tipos de expectativas críticas:", "options": ["De éxito y de fracaso", "De eficacia (autoeficacia) y de resultado", "De placer y de dolor", "Innatas y adquiridas"], "correct": 1, "justification": "Autoeficacia (¿puedo hacerlo?) y expectativa de resultado (¿servirá de algo si lo hago?). Ambas son necesarias para actuar."},
    {"question": "Si un estudiante cree firmemente que es capaz de hacer una buena exposición oral, tiene una alta:", "options": ["Disonancia cognitiva", "Motivación de deficiencia", "Expectativa de eficacia", "Regulación externa"], "correct": 2, "justification": "Confía en su capacidad para realizar la conducta requerida (autoeficacia)."}
]

new_v3 = [
    {"question": "En el experimento del juguete prohibido (Aronson y Carlsmith), los niños que recibieron una amenaza severa...", "options": ["Experimentaron mucha disonancia", "Aumentaron o mantuvieron alta su valoración del juguete, porque tenían una justificación externa suficiente para no haber jugado", "Odiaron el juguete para siempre", "Lloraron amargamente"], "correct": 1, "justification": "La amenaza severa justificaba su obediencia, por lo que no necesitaron cambiar su actitud interna hacia el juguete."},
    {"question": "En el mismo experimento del juguete prohibido, los niños con amenaza LEVE...", "options": ["Cambiaron su actitud hacia el juguete (les gustó menos) porque no tenían suficiente justificación externa para no jugar", "Rompieron el juguete", "Adoraron el juguete", "Ignoraron al educador"], "correct": 0, "justification": "Al obedecer por una amenaza pequeña, sufrieron disonancia y tuvieron que justificar internamente su conducta devaluando el juguete."},
    {"question": "La disonancia cognitiva aparece con frecuencia después de tomar decisiones difíciles entre dos alternativas atractivas. Para reducirla, solemos:", "options": ["Arrepentirnos inmediatamente y cambiar de opción", "Olvidar que tuvimos que elegir", "Justificar nuestra elección resaltando los aspectos positivos de la elegida y los negativos de la descartada", "Entrar en depresión clínica"], "correct": 2, "justification": "Esto alivia la tensión de haber renunciado a algo bueno, restaurando nuestra coherencia personal."},
    {"question": "Cuando nuestras creencias y nuestra conducta son contradictorias, Festinger postuló que se genera...", "options": ["Regulación introyectada", "Homeostasis perfecta", "Un estado de malestar psicológico y tensión llamado disonancia cognitiva", "Un instinto innato de fuga"], "correct": 2, "justification": "Esta tensión aversiva nos impulsa a modificar alguna de las dos (normalmente las creencias) para volver a ser coherentes."},
    {"question": "Una de las fuentes que nutre la expectativa de eficacia (Bandura) es la interpretación del estado fisiológico. Esto significa que:", "options": ["Comer bien asegura el éxito", "Sentirse muy nervioso o fatigado puede interpretarse como señal de baja capacidad y reducir la autoeficacia", "El corazón no afecta al cerebro", "Solo el ejercicio físico da autoeficacia"], "correct": 1, "justification": "El pánico o el temblor antes de actuar nos hace dudar de nuestra competencia; estar relajado nos da confianza."},
    {"question": "La persuasión verbal ('¡Tú puedes hacerlo!') es una forma de...", "options": ["Disonancia", "Generar expectativa de resultado", "Aumentar temporalmente la expectativa de autoeficacia mediante refuerzo social", "Engañar al cerebro"], "correct": 2, "justification": "Es una de las cuatro fuentes de autoeficacia señaladas por Bandura, aunque menos potente que la experiencia directa."},
    {"question": "En la teoría de expectativas, si creo que puedo estudiar 10 horas seguidas, pero estoy convencido de que el profesor me suspenderá igual por manía personal, entonces mi motivación caerá debido a:", "options": ["Baja autoeficacia", "Una baja expectativa de resultado", "Falta de metas", "Disonancia cognitiva extrema"], "correct": 1, "justification": "Me siento capaz de hacer la conducta (alta eficacia), pero creo que no producirá el resultado deseado (baja expectativa de resultado)."},
    {"question": "Para que las metas a corto plazo sean más motivadoras que las metas a largo plazo, la razón principal es que:", "options": ["Son más fáciles y no exigen esfuerzo", "Ofrecen más oportunidades de recibir retroalimentación (feedback) rápida sobre el progreso", "Producen más dinero", "Generan disonancia a largo plazo"], "correct": 1, "justification": "El feedback constante mantiene la sensación de competencia viva y permite ajustar la estrategia."},
    {"question": "Las metas impuestas unilateralmente por una autoridad, sin que el sujeto las acepte, suelen generar:", "options": ["El nivel máximo de rendimiento posible", "Rechazo, abandono o baja motivación, ya que carecen de compromiso personal", "Motivación intrínseca pura", "Disonancia cognitiva constructiva"], "correct": 1, "justification": "Para que la meta funcione, el sujeto debe interiorizarla y aceptarla psicológicamente como propia."},
    {"question": "En la motivación cognitiva, se asume que entre el estímulo y la respuesta motivacional...", "options": ["No hay nada, es automático", "Hay procesos mentales: interpretamos lo que ocurre y valoramos consecuencias antes de actuar", "Hay un instinto puramente biológico", "Solo existe la homeostasis de la sed"], "correct": 1, "justification": "El enfoque cognitivo rompe el mecanicismo E-R, insertando la mente (metas, expectativas, atribuciones) en el centro."},
    {"question": "¿Cuál es la forma más autónoma de motivación extrínseca en el continuo de Deci y Ryan?", "options": ["Introyectada", "Identificada", "Integrada", "Externa pura"], "correct": 2, "justification": "En la regulación integrada, la conducta impulsada extrínsecamente ha sido asimilada completamente en los valores e identidad de la persona."},
    {"question": "Las recompensas verbales, cuando se formulan de manera informativa ('muy bien, has resuelto el problema correctamente'), tienden a...", "options": ["Destruir la motivación", "Fortalecer la sensación de competencia y favorecer la motivación intrínseca", "Controlar a la persona", "Generar disonancia"], "correct": 1, "justification": "Si el elogio informa de la maestría sin sentirse como manipulación, apoya las necesidades psicológicas orgánicas."},
    {"question": "Si una recompensa o feedback se formula de forma controladora ('muy bien, has hecho justo lo que te ordené'), el efecto probable es:", "options": ["Aumento de la motivación intrínseca", "Disminución de la motivación intrínseca al atacar la necesidad de autonomía de la persona", "Mayor creatividad en el futuro", "Aparición de flow"], "correct": 1, "justification": "El sujeto percibe que su locus de causalidad vuelve a ser externo (es un títere de la autoridad), matando la motivación interna."},
    {"question": "La diferencia entre incentivos y consecuencias en la motivación extrínseca es que:", "options": ["Son exactamente lo mismo", "Los incentivos aparecen ANTES de la conducta (anticipan), las consecuencias aparecen DESPUÉS (refuerzan o castigan)", "Los incentivos son castigos, las consecuencias son premios", "Los incentivos son internos, las consecuencias externas"], "correct": 1, "justification": "El incentivo atrae o repele la acción futura; la consecuencia altera la probabilidad de que se repita la acción pasada."},
    {"question": "Si un estudiante no tiene interés en la historia, pero lee un libro de historia para evitar el castigo de sus padres, su motivación es claramente:", "options": ["Intrínseca de evitación", "Extrínseca", "De crecimiento", "Instintiva"], "correct": 1, "justification": "La fuente de energía motivacional está fuera de la actividad misma (el miedo a los padres)."},
    {"question": "Mihaly Csikszentmihalyi propuso que si el desafío de una tarea es muy bajo en relación con nuestras altas habilidades, sentiremos:", "options": ["Flow absoluto", "Pánico y estrés", "Aburrimiento", "Disonancia"], "correct": 2, "justification": "El aburrimiento surge por falta de reto, lo que impide alcanzar la absorción y concentración de la experiencia óptima."},
    {"question": "Las necesidades fisiológicas, de seguridad, de afiliación y de reconocimiento en la pirámide de Maslow se agrupan a menudo como:", "options": ["Necesidades de crecimiento", "Necesidades deficitarias (su satisfacción evita malestar)", "Necesidades instintivas animales", "Necesidades no psicológicas"], "correct": 1, "justification": "Se basan en corregir una carencia. Solo la autorrealización se considera una necesidad de 'desarrollo del ser'."},
    {"question": "La necesidad de afinidad o gregarismo (Deci y Ryan) se satisface cuando:", "options": ["Derrotamos a nuestros enemigos", "Percibimos relaciones cercanas, somos aceptados y hay ambientes sociales cálidos y de apoyo", "Nos aíslan en un bosque", "Nos pagan un salario alto"], "correct": 1, "justification": "Es la necesidad universal de pertenencia y conexión afectiva profunda con otros seres humanos."},
    {"question": "A diferencia de las teorías orgánicas, las teorías mecanicistas clásicas (ej. instintos o pulsiones estrictas) entendían al ser humano como...", "options": ["Un explorador activo de su mundo", "Un reactor pasivo frente a estímulos externos o necesidades homeostáticas internas", "Un ser puramente espiritual", "Un animal sin emociones"], "correct": 1, "justification": "Las orgánicas destacan la proactividad del ser humano para crecer; las mecanicistas lo ven como una máquina que solo busca apagar alarmas biológicas."},
    {"question": "El estudio donde pagar económicamente a mujeres por donar sangre en Gotemburgo REDUJO las donaciones es un ejemplo claro de:", "options": ["Disonancia cognitiva pura", "Cómo la motivación extrínseca monetaria puede empañar o destruir la motivación intrínseca altruista y moral", "Instinto de supervivencia", "TDAH"], "correct": 1, "justification": "Muestra el efecto nocivo de las recompensas tangibles sobre acciones impulsadas internamente por la buena voluntad."}
]

valid_v1 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 28, 29]
valid_v2 = [0, 1, 2, 3, 4, 5, 6, 13, 14, 16, 17, 21, 22, 26, 27]
valid_v3 = [0, 7, 8, 9, 10, 11, 16, 17, 21, 29]

process_file('/home/ares/Psicologia/CME/.preguntas/q_t4.js', valid_v1, new_v1, 'qT4')
process_file('/home/ares/Psicologia/CME/.preguntas/q_t4_v2.js', valid_v2, new_v2, 'qT4_v2')
process_file('/home/ares/Psicologia/CME/.preguntas/q_t4_v3.js', valid_v3, new_v3, 'qT4_v3')
